### PR TITLE
Added contributing guidelines

### LINKED ISSUE #29: add contributing.md
...and describe how to run dashboard locally and in a container

### PR DESCRIPTION
**Pull request by rishavanand**
Resolves #29 

Took reference from contributing.md of the packit-service.

I've skipped the running packit software locally section as it already covered by #31 . Let me know if it is still needed here.

### CODE REVIEW

**Comment by rishavanand** [comment]
@TomasTomecek I was trying to run dashboard in a container and found this issue. The `httpd` config is set to use `dashboard.stg.packit.dev` domain. Any other SSLCertificateFile & SSLCertificateKeyFile pair throws this error when tried to access via `localhost`:
```
SSL certificate problem: self signed certificate
``` 
How do we handle this? Do we create another `httpd` config for localhost users?

**Comment by csomh** [comment]
Using self signed certificates in local deployments, and tools raising SSL certificate issues is OK.

**Comment by rishavanand** [comment]
@csomh sorry couldn't understand,  do you mean the tools are already working fine for local deployments or me creating a tool for local deployment is okay?

**Comment by csomh** [comment]
@rishavanand nope, I meant that having SSL cert issues when deploying locally with self-signed certificates is not an issue - though I'm not sure if this is the issue you are seeing, this is just an assumption.

Please share how you tried to run the dashboard in a container, so that I can try to reproduce the same issue on my side.

**Comment by IceWreck** [comment]
I cant reproduce it either, its working fine on my machine too.

**Comment by rishavanand** [comment]
@csomh this issue is probably due to my system not trusting the locally generated SSL. Looking into it. If it doesn't work I'll list down the steps I followed.

**Comment by rishavanand** [comment]
I've added docker instructions. Should I create makefile commands to simplify the process?

**Comment by TomasTomecek** [comment]
> I've added docker instructions. Should I create makefile commands to simplify the process?

Not in this PR, please. Let's not make it too big.

**Comment by csomh** [comment]
LGTM, thanks @rishavanand!

**Pull request merged**
