### PR TITLE
Basic Setup

### PR DESCRIPTION
**Pull request by IceWreck**
Okay, this is a huge PR. I tried to document/explain how it works but lots of it is left. Ask me wherever its unclear about whats happening.

I removed (commented out) a test (reasons in a comment inside the test.py file). Recreating it would add 50,000+ lines and possibly trigger packit-service/packit-service#633
The function which it tests isnt even being used right now. One thing I can do to fix it is create a fake api with pagination to run requre once but that will be an issue again when someone needs to recreate the test.

The minified css + js bundle right now is 300KB but the same file is 9MB in development mode.
We can do two things for deployment:

- remove that file (static/dist/) from gitignore and every person who commits to this repo has to run `make transpile-prod` before committing.
- or we can continue installing all developement dependencies and make our production build in the container image itself (and maybe remove npm/yarn, node_modules etc once we have our transpiled js/css to make the comtainer image leaner)

Maybe we should not merge this right now because 
- I need to update the ansible recipe for creating that production build inside the container (will do later today)
- I removed functionality but havent added in anything so maybe leave this unmerged until it does something instead of being a boilerplate.

### CODE REVIEW

**Comment by csomh** [comment]
Thanks @IceWreck! I'll try this out tomorrow.

**Comment by csomh** [comment]
> Build failed.
> 
> * [dashboard-pre-commit ](https://softwarefactory-project.io/zuul/t/packit-service/build/cdcd272dba0744bb9271ab4d4d0dd284) : FAILURE in 3m 35s
> * [dashboard-tests ](https://softwarefactory-project.io/zuul/t/packit-service/build/715be85d515e4391aa9fa59fd7ed6aae) : FAILURE in 1m 16s

First things first: let's fix these failures :smiley:

**Comment by csomh** [comment]
Please update the commit messages to follow the rules from [How to Write a Git Commit Message](https://chris.beams.io/posts/git-commit/), as recommended in the contribution guide. I'm especially interested in commit messages clearly explaining the [what and why](https://chris.beams.io/posts/git-commit/#why-not-how) of the changes they introduce.

**Comment by csomh** [comment]
> Okay, this is a huge PR. I tried to document/explain how it works but lots of it is left. Ask me wherever its unclear about whats happening.
> 
> I removed (commented out) a test (reasons in a comment inside the test.py file). Recreating it would add 50,000+ lines and possibly trigger [packit-service/packit-service#633](https://github.com/packit-service/packit-service/issues/633)
> The function which it tests isnt even being used right now. One thing I can do to fix it is create a fake api with pagination to run requre once but that will be an issue again when someone needs to recreate the test.

Will requre be the right tool for this Flask+React setup? If not, I would say we should delete those tests and figure out a better way to test the Dashboard.

> 
> The minified css + js bundle right now is 300KB but the same file is 9MB in development mode.
> We can do two things for deployment:
> 
> * remove that file (static/dist/) from gitignore and every person who commits to this repo has to run `make transpile-prod` before committing.
> * or we can continue installing all developement dependencies and make our production build in the container image itself (and maybe remove npm/yarn, node_modules etc once we have our transpiled js/css to make the comtainer image leaner)

Definitely the second. I don't think it's a good practice to store files which can be easily regenerated in source control. As for removing build time dependencies from the container image, we should probably consider [multi-staged builds](https://fedoramagazine.org/building-smaller-container-images/).  

> 
> Maybe we should not merge this right now because
> 
> * I need to update the ansible recipe for creating that production build inside the container (will do later today)
> * I removed functionality but havent added in anything so maybe leave this unmerged until it does something instead of being a boilerplate.

I would argue to also remove all the routes and pages, except "Jobs", as populating that is the goal of the first milestone and having the others will come much later. Not having to carry dead code is good imho, and less confusing for whoever uses the Dashboard.

**Comment by IceWreck** [comment]
> Will requre be the right tool for this Flask+React setup? If not, I would say we should delete those tests and figure out a better way to test the Dashboard.

React has [ways](https://reactjs.org/docs/testing.html) of testing individual components. For the python part, we can continue using pytest. requre might be useful when/if we implement caching and want to test API requests.

For a dashboard, I think it will be better (and easier) to have end to end tests using selenium, etc but we can only do that after we implement some functionality.

> we should probably consider multi-staged builds.

Thanks, I will try this.

> I would argue to also remove all the routes and pages, except "Jobs", as populating that is the goal of the first milestone and having the others will come much later. 

👍

**Comment by lachmanfrantisek** [comment]
> Will requre be the right tool for this Flask+React setup? If not, I would say we should delete those tests and figure out a better way to test the Dashboard.

No problem with using `requre` there. We can combine that:
- Test the web content staff using flask objects directly.
- Use requre to record `api` calls to the service to not need to mock them.
  - Or, have some mocked and some using requre.

**Pull request merged**
